apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.18.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        network.host: "0.0.0.0"
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: "2"
                limits:
                  memory: 4Gi
                  cpu: "3"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
              volumeMounts:
                - name: elasticsearch-data
                  mountPath: /usr/share/elasticsearch/data
          # DO NOT manually define the readinessProbe
          # DO NOT manually mount the elasticsearch-es-elastic-user secret
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: local-path
            resources:
              requests:
                storage: 40Gi
